onEvent('jei.hide.items', e => {
	e.hide('boss_tools:steel_ingot')
	e.hide('boss_tools:steel_nugget')
	e.hide('boss_tools:steel_ingot')
	e.hide('boss_tools:steel_nugget')
	e.hide('exnihilosequentia:ingot_lead')
	e.hide('exnihilosequentia:ingot_silver')
	e.hide('exnihilosequentia:ingot_nickel')
	e.hide('boss_tools:iron_plate')
	e.hide('createaddition:diamond_grit')
	e.hide('steampowered:bronze_sheet')
	e.hide('tconstruct:tinkers_bronze_ingot')
	e.hide('oreclumps:zinc_ingot')
	e.hide('createaddition:zinc_sheet')
	e.hide('exnihilosequentia:ingot_zinc')
	e.hide('tconstruct:cobalt_ingot')
	e.hide('exnihilosequentia:ingot_aluminum')
	e.hide('exnihilosequentia:ingot_uranium')
	e.hide('oreclumps:uranium_ingot')

	e.hide('boss_tools:blast_furnace')
})

onEvent('jei.hide.fluids', e => {
	// e.hide('example:fluid')
})