#
#Elite Botany Pot Speed & OUtput
#Range: > 1
eliteBotanyPotSpeedOutput = 5
#
#Ultra Botany Pot Speed & Output
#Range: > 1
ultraBotanyPotSpeedOutput = 10
#
#Creative Botany Pot Speed & Output
#Range: > 1
creativeBotanyPotSpeedOutput = 100

