onEvent('jei.hide.items', e => {
	e.hide('boss_tools:steel_ingot')
	e.hide('immersiveengineering:plate_steel')
	e.hide('immersiveengineering:nugget_steel')
	e.hide('boss_tools:steel_nugget')
	e.hide('immersiveengineering:ingot_steel')
	e.hide('immersiveengineering:dust_steel')
	e.hide('boss_tools:steel_ingot')
	e.hide('immersiveengineering:plate_steel')
	e.hide('immersiveengineering:nugget_steel')
	e.hide('boss_tools:steel_nugget')
	e.hide('immersiveengineering:ingot_steel')
	e.hide('immersiveengineering:dust_steel')
	e.hide('immersiveengineering:ingot_lead')
	e.hide('exnihilosequentia:ingot_lead')
	e.hide('immersiveengineering:dust_lead')
	e.hide('immersiveengineering:dust_silver')
	e.hide('immersiveengineering:ingot_silver')
	e.hide('exnihilosequentia:ingot_silver')
	e.hide('immersiveengineering:plate_silver')
	e.hide('immersiveengineering:dust_nickel')
	e.hide('immersiveengineering:plate_nickel')
	e.hide('immersiveengineering:ingot_nickel')
	e.hide('exnihilosequentia:ingot_nickel')
	e.hide('immersiveengineering:dust_iron')
	e.hide('immersiveengineering:plate_iron')
	e.hide('boss_tools:iron_plate')
	e.hide('immersiveengineering:stick_iron')
	e.hide('createaddition:diamond_grit')
	e.hide('immersiveengineering:dust_constantan')
	e.hide('immersiveengineering:dust_electrum')
	e.hide('immersiveengineering:dust_hop_graphite')
	e.hide('immersiveengineering:dust_sulfur')
	e.hide('steampowered:bronze_sheet')
	e.hide('tconstruct:tinkers_bronze_ingot')
	e.hide('immersiveengineering:plate_gold')
	e.hide('immersiveengineering:dust_gold')
	e.hide('oreclumps:zinc_ingot')
	e.hide('createaddition:zinc_sheet')
	e.hide('exnihilosequentia:ingot_zinc')
	e.hide('tconstruct:cobalt_ingot')
	e.hide('immersiveengineering:dust_aluminum')
	e.hide('immersiveengineering:plate_aluminum')
	e.hide('immersiveengineering:ingot_aluminum')
	e.hide('exnihilosequentia:ingot_aluminum')
	e.hide('immersiveengineering:dust_uranium')
	e.hide('immersiveengineering:plate_uranium')
	e.hide('immersiveengineering:ingot_uranium')
	e.hide('immersiveengineering:nugget_uranium')
	e.hide('exnihilosequentia:ingot_uranium')
	e.hide('oreclumps:uranium_ingot')

	e.hide('boss_tools:blast_furnace')
})

onEvent('jei.hide.fluids', e => {
	// e.hide('example:fluid')
})